// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Secretaria.Model
{
    [Table("tbAluno")]
    [Index("CursoIdCurso", Name = "aluno_FKIndex1")]
    public partial class TbAluno
    {
        public TbAluno()
        {
            TbMatricula = new HashSet<TbMatricula>();
        }

        [Key]
        [Column("idAluno")]
        public int IdAluno { get; set; }
        [Column("curso_idCurso")]
        [Display(Name ="Nome do Curso")]
        public int CursoIdCurso { get; set; }
        [Column("nome")]
        [StringLength(100)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("cpf")]
        [StringLength(11)]
        [Unicode(false)]
        [Display(Name ="CPF")]
        public string Cpf { get; set; }
        [Column("dataInicio", TypeName = "date")]
        [Display(Name ="Data da Matrícula")]
        public DateTime? DataInicio { get; set; }

        [ForeignKey("CursoIdCurso")]
        [InverseProperty("TbAluno")]
        [Display(Name ="Curso")]
        public virtual TbCurso CursoIdCursoNavigation { get; set; }
        [InverseProperty("AlunoIdAlunoNavigation")]
        public virtual ICollection<TbMatricula> TbMatricula { get; set; }
    }
}