// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Secretaria.Model
{
    [Table("tbMatricula")]
    [Index("AlunoIdAluno", Name = "matricula_FKIndex1")]
    [Index("CursoIdCurso", Name = "matricula_FKIndex2")]
    public partial class TbMatricula
    {
        [Key]
        [Column("idMatricula")]
        public int IdMatricula { get; set; }
        [Column("curso_idCurso")]
        [Display(Name ="Nome do Curso")]
        public int CursoIdCurso { get; set; }
        [Column("aluno_idAluno")]
        [Display(Name ="Nome do Aluno")]
        public int AlunoIdAluno { get; set; }
        [Column("situacao")]
        [StringLength(20)]
        [Unicode(false)]
        [Display(Name = "Situação")]
        public string Situacao { get; set; }

        [ForeignKey("AlunoIdAluno")]
        [InverseProperty("TbMatricula")]
        [Display(Name = "Nome")]

        public virtual TbAluno AlunoIdAlunoNavigation { get; set; }
        [ForeignKey("CursoIdCurso")]
        [InverseProperty("TbMatricula")]
        [Display(Name = "Curso")]
        public virtual TbCurso CursoIdCursoNavigation { get; set; }
    }
}